module.exports = {
  'facebookAuth' : {
    'FACEBOOK_CLIENT_ID' : YOUR_FACEBOOK_CLIENT_ID,
    'FACEBOOK_CLIENT_SECRET' : YOUR_FACEBOOK_CLIENT_SECRET,
    'FACEBOOK_CALLBACKURL' : YOUR_FACEBOOK_CALLBACKURL
  }
};
