module.exports = {
  'linkedinAuth' : {
    'LINKEDIN_CLIENT_ID' : YOUR_LINKEDIN_CLIENT_ID,
    'LINKEDIN_CLIENT_SECRET' : YOUR_LINKEDIN_CLIENT_SECRET,
    'LINKEDIN_CALLBACKURL' : YOUR_LINKEDIN_CALLBACKURL
  }
};
